USE [Pupil];

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=N'dbo' AND TABLE_NAME=N'Course')
BEGIN
CREATE TABLE [dbo].[Course]
(
	[CourseID] INT PRIMARY KEY NOT NULL,
	[CourseNumber] INT NOT NULL,
	[Title] NVARCHAR(200) NOT NULL,
	[Capacity] INT NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[DateModified] DATETIME NOT NULL,
	[IsActive] BIT NOT NULL
)
END