IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA=N'dbo' AND TABLE_NAME=N'Student')
BEGIN
CREATE TABLE [dbo].[Student]
(
	[StudentID] INT PRIMARY KEY NOT NULL,
	[IDNumber] INT NOT NULL,
	[FirstName] NVARCHAR(35) NOT NULL,
	[LastName] NVARCHAR(35) NOT NULL,
	[DateCreated] DATETIME NOT NULL,
	[DateModified] DATETIME NOT NULL,
	[IsActive] BIT NOT NULL
)
END